spring:
  application:
    name: sun-moon-java-platform

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus,info
  endpoint:
    health:
      show-details: always

resilience4j:
  circuitbreaker:
    instances:
      orderEvents:
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 5s
  retry:
    instances:
      orderEvents:
        max-attempts: 3
        wait-duration: 200ms
